spring:
  datasource:
    url: jdbc:mysql://localhost:3306/summar?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_api
    password: qwer!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  security:
    enable
springdoc:
  swagger-ui:
    path: /summar-gateway-api-doc.html
    operations-sorter: method
    disable-swagger-default-url: true
    enabled: true
  api-docs:
    enabled: true